### ISSUE TITLE
contents of ../lambda.zip are not valid UTF-8

### ISSUE THREAD

**Issue by codygreen** [RSC-IoT-Open-Source/rsc-lambda-codepipeline-teams-notifications#1]
Terraform v0.12.6

**Error Message:**
Error: Error in function call

  on lambda.tf line 6, in resource "aws_lambda_function" "lambda":
   6:   source_code_hash = "${base64sha256(file("../lambda.zip"))}"

Call to function "file" failed: contents of ../lambda.zip are not valid UTF-8;
use the filebase64 function to obtain the Base64 encoded contents or the other
file functions (e.g. filemd5, filesha256) to obtain file hashing results
instead.

**Comment by codygreen** [comment]
seems to be related to this issue: [https://github.com/hashicorp/terraform/issues/21260](url)

pull request on it's way.

**Comment by jveldboom-rsc** [comment]
Closed in #2 - thanks again! 👍
